# Generated by Django 2.2.28 on 2022-06-10 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_onwer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='onwer',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='onwer',
            new_name='owner',
        ),
    ]
